#!/usr/bin/env node
/**
 * tokens/twiceover.tokens.json (DTCG, byte-identical copy of the canonical file in
 * stock-analyst-platform /ai-team/design/tokens/) -> src/styles/tokens.css
 *
 * Per ADR 0004 / consultation 0005: dependency-free; emits SEMANTIC-ONLY custom
 * properties (aliases resolved, primitives inlined — color.neutral.* / color.blue.*
 * are never exposed) plus named composite classes for the typography.* roles.
 * The output is generated at build time and gitignored — never hand-edited.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(root, "tokens/twiceover.tokens.json"), "utf8"));

/** Look up a {dot.path} reference in the token tree and return its raw $value. */
function lookup(path) {
  let node = tokens;
  for (const key of path.split(".")) {
    node = node?.[key];
    if (node === undefined) throw new Error(`Unresolvable token reference: {${path}}`);
  }
  if (node.$value === undefined) throw new Error(`Reference {${path}} has no $value`);
  return node.$value;
}

/** Resolve aliases ("{a.b}") recursively to concrete values. */
function resolve(value) {
  if (typeof value === "string") {
    const m = value.match(/^\{(.+)\}$/);
    return m ? resolve(lookup(m[1])) : value;
  }
  if (Array.isArray(value)) return value.map(resolve);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolve(v)]));
  }
  return value;
}

const css = [];
css.push("/* GENERATED by scripts/build-tokens.mjs from tokens/twiceover.tokens.json — do not edit. */");
css.push(":root {");

// Semantic color groups only — primitives (neutral.*, blue.*) are deliberately not emitted.
for (const group of ["bg", "text", "border", "accent", "focus"]) {
  for (const [name, def] of Object.entries(tokens.color[group])) {
    if (name.startsWith("$")) continue;
    css.push(`  --color-${group}-${name}: ${resolve(def.$value)};`);
  }
}

// Scales the design spec references by name (site-prelaunch.md): font, space, radius.
const fontFamily = (v) =>
  resolve(v)
    .map((f) => (f.includes(" ") || f.includes("-") ? `"${f}"` : f))
    .join(", ");
for (const [name, def] of Object.entries(tokens.font.family)) {
  if (name.startsWith("$")) continue;
  css.push(`  --font-family-${name}: ${fontFamily(def.$value)};`);
}
for (const scale of ["weight", "size", "line-height", "letter-spacing"]) {
  for (const [name, def] of Object.entries(tokens.font[scale])) {
    if (name.startsWith("$")) continue;
    css.push(`  --font-${scale}-${name}: ${resolve(def.$value)};`);
  }
}
for (const [name, def] of Object.entries(tokens.space)) {
  if (name.startsWith("$")) continue;
  css.push(`  --space-${name}: ${resolve(def.$value)};`);
}
for (const [name, def] of Object.entries(tokens.radius)) {
  if (name.startsWith("$")) continue;
  css.push(`  --radius-${name}: ${resolve(def.$value)};`);
}
css.push("}");

// Composite classes for the typography.* roles.
for (const [name, def] of Object.entries(tokens.typography)) {
  if (name.startsWith("$")) continue;
  const t = resolve(def.$value);
  css.push(`.type-${name} {`);
  css.push(`  font-family: ${t.fontFamily.map((f) => (f.includes(" ") || f.includes("-") ? `"${f}"` : f)).join(", ")};`);
  css.push(`  font-size: ${t.fontSize};`);
  css.push(`  font-weight: ${t.fontWeight};`);
  css.push(`  line-height: ${t.lineHeight};`);
  css.push(`  letter-spacing: ${t.letterSpacing};`);
  css.push(`}`);
}

const out = join(root, "src/styles/tokens.css");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css.join("\n") + "\n");
console.log(`tokens.css written (${css.length} lines) from tokens v${/v(\d+\.\d+\.\d+)/.exec(tokens.$description)?.[1] ?? "?"}`);
